// // <auto-generated />
// using System;
// using Backend.Data;
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Metadata;
// using Microsoft.EntityFrameworkCore.Migrations;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

// #nullable disable

// namespace Backend.Migrations
// {
//     [DbContext(typeof(DatabaseContext))]
//     [Migration("20250224203703_addManagerIdTOTenant")]
//     partial class addManagerIdTOTenant
//     {
//         /// <inheritdoc />
//         protected override void BuildTargetModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder
//                 .HasAnnotation("ProductVersion", "8.0.10")
//                 .HasAnnotation("Relational:MaxIdentifierLength", 128);

//             SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//             modelBuilder.Entity("Backend.Models.AccountStudentGuardian", b =>
//                 {
//                     b.Property<int>("AccountStudentGuardianID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountStudentGuardianID"));

//                     b.Property<int>("AccountID")
//                         .HasColumnType("int");

//                     b.Property<decimal>("Amount")
//                         .HasColumnType("decimal(18,2)");

//                     b.Property<int>("GuardianID")
//                         .HasColumnType("int");

//                     b.Property<int>("StudentID")
//                         .HasColumnType("int");

//                     b.HasKey("AccountStudentGuardianID");

//                     b.HasIndex("AccountID");

//                     b.HasIndex("GuardianID");

//                     b.HasIndex("StudentID");

//                     b.ToTable("AccountStudentGuardians");
//                 });

//             modelBuilder.Entity("Backend.Models.Accounts", b =>
//                 {
//                     b.Property<int>("AccountID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

//                     b.Property<DateTime>("HireDate")
//                         .HasColumnType("datetime2");

//                     b.Property<string>("Note")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<decimal?>("OpenBalance")
//                         .HasColumnType("decimal(18,2)");

//                     b.Property<bool>("State")
//                         .HasColumnType("bit");

//                     b.Property<int>("TypeAccountID")
//                         .HasColumnType("int");

//                     b.Property<bool>("TypeOpenBalance")
//                         .HasColumnType("bit");

//                     b.HasKey("AccountID");

//                     b.HasIndex("TypeAccountID");

//                     b.ToTable("Accounts");
//                 });

//             modelBuilder.Entity("Backend.Models.ApplicationUser", b =>
//                 {
//                     b.Property<string>("Id")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<int>("AccessFailedCount")
//                         .HasColumnType("int");

//                     b.Property<string>("Address")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("ConcurrencyStamp")
//                         .IsConcurrencyToken()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Email")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.Property<bool>("EmailConfirmed")
//                         .HasColumnType("bit");

//                     b.Property<string>("Gender")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<DateTime>("HireDate")
//                         .HasColumnType("datetime2");

//                     b.Property<bool>("LockoutEnabled")
//                         .HasColumnType("bit");

//                     b.Property<DateTimeOffset?>("LockoutEnd")
//                         .HasColumnType("datetimeoffset");

//                     b.Property<string>("NormalizedEmail")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.Property<string>("NormalizedUserName")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.Property<string>("PasswordHash")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("PhoneNumber")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<bool>("PhoneNumberConfirmed")
//                         .HasColumnType("bit");

//                     b.Property<string>("SecurityStamp")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<bool>("TwoFactorEnabled")
//                         .HasColumnType("bit");

//                     b.Property<string>("UserName")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.Property<string>("UserType")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("Id");

//                     b.HasIndex("NormalizedEmail")
//                         .HasDatabaseName("EmailIndex");

//                     b.HasIndex("NormalizedUserName")
//                         .IsUnique()
//                         .HasDatabaseName("UserNameIndex")
//                         .HasFilter("[NormalizedUserName] IS NOT NULL");

//                     b.ToTable("AspNetUsers", (string)null);

//                     b.HasData(
//                         new
//                         {
//                             Id = "007266f8-a4b4-4b9e-a8d2-3e0a6f9df5ec",
//                             AccessFailedCount = 0,
//                             ConcurrencyStamp = "bedf0368-927a-4b68-96f7-2dd27b4fa6a3",
//                             Email = "admin@gmail.com",
//                             EmailConfirmed = true,
//                             Gender = "",
//                             HireDate = new DateTime(2025, 2, 24, 23, 37, 2, 177, DateTimeKind.Local).AddTicks(5970),
//                             LockoutEnabled = false,
//                             NormalizedEmail = "ADMIN@GMAIL.COM",
//                             NormalizedUserName = "ADMIN",
//                             PasswordHash = "AQAAAAIAAYagAAAAEMe94oJi7E1DeSPGLVvUnlSxMRk6SLF16KE0zVs1FBoiLQzcOQE2BOFx6sFcsVvXUA==",
//                             PhoneNumberConfirmed = false,
//                             SecurityStamp = "d98c7782-2ac9-40ef-adda-5f2330458967",
//                             TwoFactorEnabled = false,
//                             UserName = "Admin",
//                             UserType = "Admin"
//                         });
//                 });

//             modelBuilder.Entity("Backend.Models.Attachments", b =>
//                 {
//                     b.Property<int>("AttachmentID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentID"));

//                     b.Property<string>("AttachmentURL")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Note")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int?>("StudentID")
//                         .HasColumnType("int");

//                     b.Property<int?>("VoucherID")
//                         .HasColumnType("int");

//                     b.HasKey("AttachmentID");

//                     b.HasIndex("StudentID");

//                     b.HasIndex("VoucherID");

//                     b.ToTable("Attachments");
//                 });

//             modelBuilder.Entity("Backend.Models.Class", b =>
//                 {
//                     b.Property<int>("ClassID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

//                     b.Property<string>("ClassName")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("ClassYear")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int>("StageID")
//                         .HasColumnType("int");

//                     b.Property<bool>("State")
//                         .HasColumnType("bit");

//                     b.HasKey("ClassID");

//                     b.HasIndex("StageID");

//                     b.ToTable("Classes");
//                 });

//             modelBuilder.Entity("Backend.Models.Division", b =>
//                 {
//                     b.Property<int>("DivisionID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionID"));

//                     b.Property<int>("ClassID")
//                         .HasColumnType("int");

//                     b.Property<string>("DivisionName")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<bool>("State")
//                         .HasColumnType("bit");

//                     b.HasKey("DivisionID");

//                     b.HasIndex("ClassID");

//                     b.ToTable("Divisions");
//                 });

//             modelBuilder.Entity("Backend.Models.Fee", b =>
//                 {
//                     b.Property<int>("FeeID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeID"));

//                     b.Property<string>("FeeName")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("FeeNameAlis")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<DateTime>("HireDate")
//                         .HasColumnType("datetime2");

//                     b.Property<string>("Note")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<bool>("State")
//                         .HasColumnType("bit");

//                     b.HasKey("FeeID");

//                     b.ToTable("Fees");
//                 });

//             modelBuilder.Entity("Backend.Models.FeeClass", b =>
//                 {
//                     b.Property<int>("FeeClassID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeClassID"));

//                     b.Property<double?>("Amount")
//                         .HasColumnType("float");

//                     b.Property<int>("ClassID")
//                         .HasColumnType("int");

//                     b.Property<int>("FeeID")
//                         .HasColumnType("int");

//                     b.Property<bool>("Mandatory")
//                         .HasColumnType("bit");

//                     b.HasKey("FeeClassID");

//                     b.HasIndex("ClassID");

//                     b.HasIndex("FeeID");

//                     b.ToTable("FeeClass");
//                 });

//             modelBuilder.Entity("Backend.Models.Guardian", b =>
//                 {
//                     b.Property<int>("GuardianID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuardianID"));

//                     b.Property<string>("FullName")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<DateTime?>("GuardianDOB")
//                         .HasColumnType("datetime2");

//                     b.Property<string>("Type")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("UserID")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("GuardianID");

//                     b.HasIndex("UserID")
//                         .IsUnique();

//                     b.ToTable("Guardians");
//                 });

//             modelBuilder.Entity("Backend.Models.Manager", b =>
//                 {
//                     b.Property<int>("ManagerID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerID"));

//                     b.Property<int>("SchoolID")
//                         .HasColumnType("int");

//                     b.Property<string>("UserID")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("ManagerID");

//                     b.HasIndex("SchoolID")
//                         .IsUnique();

//                     b.HasIndex("UserID")
//                         .IsUnique();

//                     b.ToTable("Managers");
//                 });

//             modelBuilder.Entity("Backend.Models.Salary", b =>
//                 {
//                     b.Property<int>("SalaryID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryID"));

//                     b.Property<string>("Note")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int>("SalaryAmount")
//                         .HasColumnType("int");

//                     b.Property<DateTime>("SalaryHireDate")
//                         .HasColumnType("datetime2");

//                     b.Property<DateTime>("SalaryMonth")
//                         .HasColumnType("datetime2");

//                     b.Property<int>("TeacherID")
//                         .HasColumnType("int");

//                     b.HasKey("SalaryID");

//                     b.HasIndex("TeacherID");

//                     b.ToTable("Salarys");
//                 });

//             modelBuilder.Entity("Backend.Models.School", b =>
//                 {
//                     b.Property<int>("SchoolID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolID"));

//                     b.Property<string>("Address")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("City")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Country")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Description")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Email")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<DateTime>("HireDate")
//                         .HasColumnType("datetime2");

//                     b.Property<string>("Mobile")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Notes")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("SchoolCategory")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("SchoolGoal")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("SchoolMission")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("SchoolName")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("SchoolNameEn")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int>("SchoolPhone")
//                         .HasColumnType("int");

//                     b.Property<string>("SchoolType")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("SchoolVison")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Street")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Website")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int?>("fax")
//                         .HasColumnType("int");

//                     b.Property<string>("zone")
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("SchoolID");

//                     b.ToTable("Schools");
//                 });

//             modelBuilder.Entity("Backend.Models.Stage", b =>
//                 {
//                     b.Property<int>("StageID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageID"));

//                     b.Property<bool>("Active")
//                         .HasColumnType("bit");

//                     b.Property<DateTime>("HireDate")
//                         .HasColumnType("datetime2");

//                     b.Property<string>("Note")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("StageName")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int>("YearID")
//                         .HasColumnType("int");

//                     b.HasKey("StageID");

//                     b.HasIndex("YearID");

//                     b.ToTable("Stages");
//                 });

//             modelBuilder.Entity("Backend.Models.Student", b =>
//                 {
//                     b.Property<int>("StudentID")
//                         .HasColumnType("int");

//                     b.Property<int>("DivisionID")
//                         .HasColumnType("int");

//                     b.Property<int>("GuardianID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int")
//                         .HasDefaultValue(1012);

//                     b.Property<string>("ImageURL")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("PlaceBirth")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<DateTime?>("StudentDOB")
//                         .HasColumnType("datetime2");

//                     b.Property<string>("UserID")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("StudentID");

//                     b.HasIndex("DivisionID");

//                     b.HasIndex("GuardianID");

//                     b.HasIndex("UserID")
//                         .IsUnique();

//                     b.ToTable("Students");
//                 });

//             modelBuilder.Entity("Backend.Models.StudentClassFees", b =>
//                 {
//                     b.Property<int>("StudentClassFeesID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentClassFeesID"));

//                     b.Property<decimal?>("AmountDiscount")
//                         .HasColumnType("decimal(18,2)");

//                     b.Property<int>("FeeClassID")
//                         .HasColumnType("int");

//                     b.Property<string>("NoteDiscount")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int>("StudentID")
//                         .HasColumnType("int");

//                     b.HasKey("StudentClassFeesID");

//                     b.HasIndex("FeeClassID");

//                     b.HasIndex("StudentID");

//                     b.ToTable("StudentClassFees");
//                 });

//             modelBuilder.Entity("Backend.Models.Subject", b =>
//                 {
//                     b.Property<int>("SubjectID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

//                     b.Property<int>("ClassID")
//                         .HasColumnType("int");

//                     b.Property<string>("SubjectName")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("SubjectID");

//                     b.HasIndex("ClassID");

//                     b.ToTable("Subjects");
//                 });

//             modelBuilder.Entity("Backend.Models.SubjectStudent", b =>
//                 {
//                     b.Property<int>("SubjectID")
//                         .HasColumnType("int");

//                     b.Property<int>("StudentID")
//                         .HasColumnType("int");

//                     b.Property<int>("Grade")
//                         .HasColumnType("int");

//                     b.HasKey("SubjectID", "StudentID");

//                     b.HasIndex("StudentID");

//                     b.ToTable("SubjectStudents");
//                 });

//             modelBuilder.Entity("Backend.Models.Teacher", b =>
//                 {
//                     b.Property<int>("TeacherID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

//                     b.Property<int>("ManagerID")
//                         .HasColumnType("int");

//                     b.Property<string>("UserID")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("TeacherID");

//                     b.HasIndex("ManagerID");

//                     b.HasIndex("UserID")
//                         .IsUnique();

//                     b.ToTable("Teachers");
//                 });

//             modelBuilder.Entity("Backend.Models.TeacherStudent", b =>
//                 {
//                     b.Property<int>("StudentID")
//                         .HasColumnType("int");

//                     b.Property<int>("TeacherID")
//                         .HasColumnType("int");

//                     b.HasKey("StudentID", "TeacherID");

//                     b.HasIndex("TeacherID");

//                     b.ToTable("TeacherStudents");
//                 });

//             modelBuilder.Entity("Backend.Models.TeacherSubjectStudent", b =>
//                 {
//                     b.Property<int>("TeacherID")
//                         .HasColumnType("int");

//                     b.Property<int>("StudentID")
//                         .HasColumnType("int");

//                     b.Property<int>("SubjectID")
//                         .HasColumnType("int");

//                     b.HasKey("TeacherID", "StudentID", "SubjectID");

//                     b.HasIndex("StudentID");

//                     b.HasIndex("SubjectID");

//                     b.ToTable("TeacherSubjectStudent");
//                 });

//             modelBuilder.Entity("Backend.Models.Tenant", b =>
//                 {
//                     b.Property<int>("TenantId")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

//                     b.Property<string>("ConnectionString")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int?>("ManagerId")
//                         .HasColumnType("int");

//                     b.Property<string>("SchoolName")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("TenantId");

//                     b.HasIndex("ManagerId")
//                         .IsUnique()
//                         .HasFilter("[ManagerId] IS NOT NULL");

//                     b.ToTable("Tenants");
//                 });

//             modelBuilder.Entity("Backend.Models.TypeAccount", b =>
//                 {
//                     b.Property<int>("TypeAccountID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeAccountID"));

//                     b.Property<string>("TypeAccountName")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("TypeAccountID");

//                     b.ToTable("TypeAccounts");

//                     b.HasData(
//                         new
//                         {
//                             TypeAccountID = 1,
//                             TypeAccountName = "Guardain"
//                         },
//                         new
//                         {
//                             TypeAccountID = 2,
//                             TypeAccountName = "School"
//                         },
//                         new
//                         {
//                             TypeAccountID = 3,
//                             TypeAccountName = "Branches"
//                         },
//                         new
//                         {
//                             TypeAccountID = 4,
//                             TypeAccountName = "Funds"
//                         },
//                         new
//                         {
//                             TypeAccountID = 5,
//                             TypeAccountName = "Employees"
//                         },
//                         new
//                         {
//                             TypeAccountID = 6,
//                             TypeAccountName = "Banks"
//                         });
//                 });

//             modelBuilder.Entity("Backend.Models.Vouchers", b =>
//                 {
//                     b.Property<int>("VoucherID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherID"));

//                     b.Property<int>("AccountStudentGuardianID")
//                         .HasColumnType("int");

//                     b.Property<DateTime>("HireDate")
//                         .HasColumnType("datetime2");

//                     b.Property<string>("Note")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("PayBy")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<decimal>("Receipt")
//                         .HasColumnType("decimal(18,2)");

//                     b.HasKey("VoucherID");

//                     b.HasIndex("AccountStudentGuardianID");

//                     b.ToTable("vouchers");
//                 });

//             modelBuilder.Entity("Backend.Models.Year", b =>
//                 {
//                     b.Property<int>("YearID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YearID"));

//                     b.Property<bool>("Active")
//                         .HasColumnType("bit");

//                     b.Property<DateTime>("HireDate")
//                         .HasColumnType("datetime2");

//                     b.Property<int>("SchoolID")
//                         .HasColumnType("int");

//                     b.Property<DateTime?>("YearDateEnd")
//                         .HasColumnType("datetime2");

//                     b.Property<DateTime>("YearDateStart")
//                         .HasColumnType("datetime2");

//                     b.HasKey("YearID");

//                     b.HasIndex("SchoolID");

//                     b.ToTable("Years");
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
//                 {
//                     b.Property<string>("Id")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("ConcurrencyStamp")
//                         .IsConcurrencyToken()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Name")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.Property<string>("NormalizedName")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.HasKey("Id");

//                     b.HasIndex("NormalizedName")
//                         .IsUnique()
//                         .HasDatabaseName("RoleNameIndex")
//                         .HasFilter("[NormalizedName] IS NOT NULL");

//                     b.ToTable("AspNetRoles", (string)null);

//                     b.HasData(
//                         new
//                         {
//                             Id = "1",
//                             Name = "MANAGER",
//                             NormalizedName = "MANAGER"
//                         },
//                         new
//                         {
//                             Id = "2",
//                             Name = "STUDENT",
//                             NormalizedName = "STUDENT"
//                         },
//                         new
//                         {
//                             Id = "3",
//                             Name = "TEACHER",
//                             NormalizedName = "TEACHER"
//                         },
//                         new
//                         {
//                             Id = "4",
//                             Name = "GUARDIAN",
//                             NormalizedName = "GUARDIAN"
//                         });
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                     b.Property<string>("ClaimType")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("ClaimValue")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("RoleId")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("Id");

//                     b.HasIndex("RoleId");

//                     b.ToTable("AspNetRoleClaims", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                     b.Property<string>("ClaimType")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("ClaimValue")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("UserId")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("Id");

//                     b.HasIndex("UserId");

//                     b.ToTable("AspNetUserClaims", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                 {
//                     b.Property<string>("LoginProvider")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("ProviderKey")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("ProviderDisplayName")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("UserId")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("LoginProvider", "ProviderKey");

//                     b.HasIndex("UserId");

//                     b.ToTable("AspNetUserLogins", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                 {
//                     b.Property<string>("UserId")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("RoleId")
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("UserId", "RoleId");

//                     b.HasIndex("RoleId");

//                     b.ToTable("AspNetUserRoles", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                 {
//                     b.Property<string>("UserId")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("LoginProvider")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("Name")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("Value")
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("UserId", "LoginProvider", "Name");

//                     b.ToTable("AspNetUserTokens", (string)null);
//                 });

//             modelBuilder.Entity("Backend.Models.AccountStudentGuardian", b =>
//                 {
//                     b.HasOne("Backend.Models.Accounts", "Accounts")
//                         .WithMany("AccountStudentGuardians")
//                         .HasForeignKey("AccountID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.HasOne("Backend.Models.Guardian", "Guardian")
//                         .WithMany("AccountStudentGuardians")
//                         .HasForeignKey("GuardianID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.HasOne("Backend.Models.Student", "Student")
//                         .WithMany("AccountStudentGuardians")
//                         .HasForeignKey("StudentID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("Accounts");

//                     b.Navigation("Guardian");

//                     b.Navigation("Student");
//                 });

//             modelBuilder.Entity("Backend.Models.Accounts", b =>
//                 {
//                     b.HasOne("Backend.Models.TypeAccount", "TypeAccount")
//                         .WithMany("Accounts")
//                         .HasForeignKey("TypeAccountID")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("TypeAccount");
//                 });

//             modelBuilder.Entity("Backend.Models.Attachments", b =>
//                 {
//                     b.HasOne("Backend.Models.Student", "Student")
//                         .WithMany("Attachments")
//                         .HasForeignKey("StudentID")
//                         .OnDelete(DeleteBehavior.Cascade);

//                     b.HasOne("Backend.Models.Vouchers", "Vouchers")
//                         .WithMany("Attachments")
//                         .HasForeignKey("VoucherID")
//                         .OnDelete(DeleteBehavior.Cascade);

//                     b.Navigation("Student");

//                     b.Navigation("Vouchers");
//                 });

//             modelBuilder.Entity("Backend.Models.Class", b =>
//                 {
//                     b.HasOne("Backend.Models.Stage", "Stage")
//                         .WithMany("Classes")
//                         .HasForeignKey("StageID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("Stage");
//                 });

//             modelBuilder.Entity("Backend.Models.Division", b =>
//                 {
//                     b.HasOne("Backend.Models.Class", "Class")
//                         .WithMany("Divisions")
//                         .HasForeignKey("ClassID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("Class");
//                 });

//             modelBuilder.Entity("Backend.Models.FeeClass", b =>
//                 {
//                     b.HasOne("Backend.Models.Class", "Class")
//                         .WithMany("FeeClasses")
//                         .HasForeignKey("ClassID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.HasOne("Backend.Models.Fee", "Fee")
//                         .WithMany("FeeClasses")
//                         .HasForeignKey("FeeID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("Class");

//                     b.Navigation("Fee");
//                 });

//             modelBuilder.Entity("Backend.Models.Guardian", b =>
//                 {
//                     b.HasOne("Backend.Models.ApplicationUser", "ApplicationUser")
//                         .WithOne("Guardian")
//                         .HasForeignKey("Backend.Models.Guardian", "UserID")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("ApplicationUser");
//                 });

//             modelBuilder.Entity("Backend.Models.Manager", b =>
//                 {
//                     b.HasOne("Backend.Models.School", "School")
//                         .WithOne("Manager")
//                         .HasForeignKey("Backend.Models.Manager", "SchoolID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.HasOne("Backend.Models.ApplicationUser", "ApplicationUser")
//                         .WithOne("Manager")
//                         .HasForeignKey("Backend.Models.Manager", "UserID")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.OwnsOne("Backend.Models.Name", "FullName", b1 =>
//                         {
//                             b1.Property<int>("ManagerID")
//                                 .HasColumnType("int");

//                             b1.Property<string>("FirstName")
//                                 .IsRequired()
//                                 .HasColumnType("nvarchar(max)");

//                             b1.Property<string>("LastName")
//                                 .IsRequired()
//                                 .HasColumnType("nvarchar(max)");

//                             b1.Property<string>("MiddleName")
//                                 .IsRequired()
//                                 .HasColumnType("nvarchar(max)");

//                             b1.HasKey("ManagerID");

//                             b1.ToTable("Managers");

//                             b1.WithOwner()
//                                 .HasForeignKey("ManagerID");
//                         });

//                     b.Navigation("ApplicationUser");

//                     b.Navigation("FullName")
//                         .IsRequired();

//                     b.Navigation("School");
//                 });

//             modelBuilder.Entity("Backend.Models.Salary", b =>
//                 {
//                     b.HasOne("Backend.Models.Teacher", "Teacher")
//                         .WithMany("Salaries")
//                         .HasForeignKey("TeacherID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("Teacher");
//                 });

//             modelBuilder.Entity("Backend.Models.Stage", b =>
//                 {
//                     b.HasOne("Backend.Models.Year", "Year")
//                         .WithMany("Stages")
//                         .HasForeignKey("YearID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("Year");
//                 });

//             modelBuilder.Entity("Backend.Models.Student", b =>
//                 {
//                     b.HasOne("Backend.Models.Division", "Division")
//                         .WithMany("Students")
//                         .HasForeignKey("DivisionID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.HasOne("Backend.Models.Guardian", "Guardian")
//                         .WithMany("Students")
//                         .HasForeignKey("GuardianID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.HasOne("Backend.Models.ApplicationUser", "ApplicationUser")
//                         .WithOne("Student")
//                         .HasForeignKey("Backend.Models.Student", "UserID")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.OwnsOne("Backend.Models.NameAlis", "FullNameAlis", b1 =>
//                         {
//                             b1.Property<int>("StudentID")
//                                 .HasColumnType("int");

//                             b1.Property<string>("FirstNameEng")
//                                 .HasColumnType("nvarchar(max)");

//                             b1.Property<string>("LastNameEng")
//                                 .HasColumnType("nvarchar(max)");

//                             b1.Property<string>("MiddleNameEng")
//                                 .HasColumnType("nvarchar(max)");

//                             b1.HasKey("StudentID");

//                             b1.ToTable("Students");

//                             b1.WithOwner()
//                                 .HasForeignKey("StudentID");
//                         });

//                     b.OwnsOne("Backend.Models.Name", "FullName", b1 =>
//                         {
//                             b1.Property<int>("StudentID")
//                                 .HasColumnType("int");

//                             b1.Property<string>("FirstName")
//                                 .IsRequired()
//                                 .HasColumnType("nvarchar(max)");

//                             b1.Property<string>("LastName")
//                                 .IsRequired()
//                                 .HasColumnType("nvarchar(max)");

//                             b1.Property<string>("MiddleName")
//                                 .IsRequired()
//                                 .HasColumnType("nvarchar(max)");

//                             b1.HasKey("StudentID");

//                             b1.ToTable("Students");

//                             b1.WithOwner()
//                                 .HasForeignKey("StudentID");
//                         });

//                     b.Navigation("ApplicationUser");

//                     b.Navigation("Division");

//                     b.Navigation("FullName")
//                         .IsRequired();

//                     b.Navigation("FullNameAlis");

//                     b.Navigation("Guardian");
//                 });

//             modelBuilder.Entity("Backend.Models.StudentClassFees", b =>
//                 {
//                     b.HasOne("Backend.Models.FeeClass", "FeeClass")
//                         .WithMany("StudentClassFees")
//                         .HasForeignKey("FeeClassID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.HasOne("Backend.Models.Student", "Student")
//                         .WithMany("StudentClassFees")
//                         .HasForeignKey("StudentID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("FeeClass");

//                     b.Navigation("Student");
//                 });

//             modelBuilder.Entity("Backend.Models.Subject", b =>
//                 {
//                     b.HasOne("Backend.Models.Class", "Class")
//                         .WithMany("Subjects")
//                         .HasForeignKey("ClassID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("Class");
//                 });

//             modelBuilder.Entity("Backend.Models.SubjectStudent", b =>
//                 {
//                     b.HasOne("Backend.Models.Student", "Student")
//                         .WithMany("SubjectStudents")
//                         .HasForeignKey("StudentID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.HasOne("Backend.Models.Subject", "Subject")
//                         .WithMany("SubjectStudents")
//                         .HasForeignKey("SubjectID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("Student");

//                     b.Navigation("Subject");
//                 });

//             modelBuilder.Entity("Backend.Models.Teacher", b =>
//                 {
//                     b.HasOne("Backend.Models.Manager", "Manager")
//                         .WithMany("Teachers")
//                         .HasForeignKey("ManagerID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.HasOne("Backend.Models.ApplicationUser", "ApplicationUser")
//                         .WithOne("Teacher")
//                         .HasForeignKey("Backend.Models.Teacher", "UserID")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.OwnsOne("Backend.Models.Name", "FullName", b1 =>
//                         {
//                             b1.Property<int>("TeacherID")
//                                 .HasColumnType("int");

//                             b1.Property<string>("FirstName")
//                                 .IsRequired()
//                                 .HasColumnType("nvarchar(max)");

//                             b1.Property<string>("LastName")
//                                 .IsRequired()
//                                 .HasColumnType("nvarchar(max)");

//                             b1.Property<string>("MiddleName")
//                                 .IsRequired()
//                                 .HasColumnType("nvarchar(max)");

//                             b1.HasKey("TeacherID");

//                             b1.ToTable("Teachers");

//                             b1.WithOwner()
//                                 .HasForeignKey("TeacherID");
//                         });

//                     b.Navigation("ApplicationUser");

//                     b.Navigation("FullName")
//                         .IsRequired();

//                     b.Navigation("Manager");
//                 });

//             modelBuilder.Entity("Backend.Models.TeacherStudent", b =>
//                 {
//                     b.HasOne("Backend.Models.Student", "Student")
//                         .WithMany("TeacherStudents")
//                         .HasForeignKey("StudentID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.HasOne("Backend.Models.Teacher", "Teacher")
//                         .WithMany("TeacherStudents")
//                         .HasForeignKey("TeacherID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("Student");

//                     b.Navigation("Teacher");
//                 });

//             modelBuilder.Entity("Backend.Models.TeacherSubjectStudent", b =>
//                 {
//                     b.HasOne("Backend.Models.Student", "Student")
//                         .WithMany("TeacherSubjectStudents")
//                         .HasForeignKey("StudentID")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("Backend.Models.Subject", "Subject")
//                         .WithMany("TeacherSubjectStudents")
//                         .HasForeignKey("SubjectID")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("Backend.Models.Teacher", "Teacher")
//                         .WithMany("TeacherSubjectStudents")
//                         .HasForeignKey("TeacherID")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("Student");

//                     b.Navigation("Subject");

//                     b.Navigation("Teacher");
//                 });

//             modelBuilder.Entity("Backend.Models.Tenant", b =>
//                 {
//                     b.HasOne("Backend.Models.Manager", "Manager")
//                         .WithOne("Tenant")
//                         .HasForeignKey("Backend.Models.Tenant", "ManagerId")
//                         .OnDelete(DeleteBehavior.Restrict);

//                     b.Navigation("Manager");
//                 });

//             modelBuilder.Entity("Backend.Models.Vouchers", b =>
//                 {
//                     b.HasOne("Backend.Models.AccountStudentGuardian", "AccountStudentGuardians")
//                         .WithMany("Vouchers")
//                         .HasForeignKey("AccountStudentGuardianID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("AccountStudentGuardians");
//                 });

//             modelBuilder.Entity("Backend.Models.Year", b =>
//                 {
//                     b.HasOne("Backend.Models.School", "School")
//                         .WithMany("Years")
//                         .HasForeignKey("SchoolID")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("School");
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                         .WithMany()
//                         .HasForeignKey("RoleId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                 {
//                     b.HasOne("Backend.Models.ApplicationUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                 {
//                     b.HasOne("Backend.Models.ApplicationUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                         .WithMany()
//                         .HasForeignKey("RoleId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("Backend.Models.ApplicationUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                 {
//                     b.HasOne("Backend.Models.ApplicationUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("Backend.Models.AccountStudentGuardian", b =>
//                 {
//                     b.Navigation("Vouchers");
//                 });

//             modelBuilder.Entity("Backend.Models.Accounts", b =>
//                 {
//                     b.Navigation("AccountStudentGuardians");
//                 });

//             modelBuilder.Entity("Backend.Models.ApplicationUser", b =>
//                 {
//                     b.Navigation("Guardian");

//                     b.Navigation("Manager");

//                     b.Navigation("Student");

//                     b.Navigation("Teacher");
//                 });

//             modelBuilder.Entity("Backend.Models.Class", b =>
//                 {
//                     b.Navigation("Divisions");

//                     b.Navigation("FeeClasses");

//                     b.Navigation("Subjects");
//                 });

//             modelBuilder.Entity("Backend.Models.Division", b =>
//                 {
//                     b.Navigation("Students");
//                 });

//             modelBuilder.Entity("Backend.Models.Fee", b =>
//                 {
//                     b.Navigation("FeeClasses");
//                 });

//             modelBuilder.Entity("Backend.Models.FeeClass", b =>
//                 {
//                     b.Navigation("StudentClassFees");
//                 });

//             modelBuilder.Entity("Backend.Models.Guardian", b =>
//                 {
//                     b.Navigation("AccountStudentGuardians");

//                     b.Navigation("Students");
//                 });

//             modelBuilder.Entity("Backend.Models.Manager", b =>
//                 {
//                     b.Navigation("Teachers");

//                     b.Navigation("Tenant")
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("Backend.Models.School", b =>
//                 {
//                     b.Navigation("Manager")
//                         .IsRequired();

//                     b.Navigation("Years");
//                 });

//             modelBuilder.Entity("Backend.Models.Stage", b =>
//                 {
//                     b.Navigation("Classes");
//                 });

//             modelBuilder.Entity("Backend.Models.Student", b =>
//                 {
//                     b.Navigation("AccountStudentGuardians");

//                     b.Navigation("Attachments");

//                     b.Navigation("StudentClassFees");

//                     b.Navigation("SubjectStudents");

//                     b.Navigation("TeacherStudents");

//                     b.Navigation("TeacherSubjectStudents");
//                 });

//             modelBuilder.Entity("Backend.Models.Subject", b =>
//                 {
//                     b.Navigation("SubjectStudents");

//                     b.Navigation("TeacherSubjectStudents");
//                 });

//             modelBuilder.Entity("Backend.Models.Teacher", b =>
//                 {
//                     b.Navigation("Salaries");

//                     b.Navigation("TeacherStudents");

//                     b.Navigation("TeacherSubjectStudents");
//                 });

//             modelBuilder.Entity("Backend.Models.TypeAccount", b =>
//                 {
//                     b.Navigation("Accounts");
//                 });

//             modelBuilder.Entity("Backend.Models.Vouchers", b =>
//                 {
//                     b.Navigation("Attachments");
//                 });

//             modelBuilder.Entity("Backend.Models.Year", b =>
//                 {
//                     b.Navigation("Stages");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }
